version: '3.9'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./minor_server/source/database_schemas:/docker-entrypoint-initdb.d
      - userdata:/var/lib/postgresql/data/pgdata
    networks:
      - server_network
    restart: unless-stopped

  minor_server:
    container_name: minor_server
    image: minor_server
    platform: linux/amd64
    build: .
    ports:
      - "8080:8080"
    networks:
      - server_network
    restart: always

volumes:
  userdata:

networks:
  server_network:
    driver: bridge